# Generated by Django 3.1.2 on 2020-10-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('Latitude', models.FloatField(help_text='Latitude', max_length=10)),
                ('Longitude', models.FloatField(help_text='Longitude', max_length=10)),
                ('Squirrel_ID', models.CharField(default=None, help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=100)),
                ('Date', models.DateField(blank=True, help_text='Date')),
            ],
        ),
    ]
