# Generated by Django 3.1.2 on 2020-10-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Squirrels',
            new_name='Squirrel',
        ),
    ]
