# Generated by Django 3.1.2 on 2020-10-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201018_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, help_text='Age', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(help_text='Whether or not squirrel is chasing', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(help_text='Whether or not squirrel is climbing', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(help_text='Whether or not squirrel is eating', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(help_text='Whether or not squirrel is foraging', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Fur_Color',
            field=models.CharField(blank=True, help_text='Primary Fur Color', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, help_text='Location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(help_text='Whether or not squirrel is running', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100, null=True),
        ),
    ]
