# Generated by Django 3.1.2 on 2020-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201018_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(help_text='Whether or not squirrel approaches', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(help_text='Whether or not squirrel is indifferent', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(help_text='Kuks', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(help_text='Moans', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(help_text='Quaas', null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_From',
            field=models.CharField(blank=True, help_text='Where the squirrel is running from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(help_text="Whether or not squirrel's tail flag", null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(help_text="Whether or not squirrel's tail twitch", null=True),
        ),
    ]
