# Generated by Django 3.1.2 on 2020-10-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20201018_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Squirrel_ID',
            new_name='Unique_Squirrel_ID',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Latitude',
            new_name='X',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longitude',
            new_name='Y',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Fur_Color',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamom', 'Cinnamom'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground_Plane', 'Ground Plane')], help_text='Location', max_length=100, null=True),
        ),
    ]
