# Generated by Django 3.1.2 on 2020-10-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20201018_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Unique_Squirrel_ID',
            new_name='Squirrel_ID',
        ),
    ]
