# Generated by Django 3.1.2 on 2020-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0006_auto_20201018_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(help_text='Where the squirrel is running from', null=True),
        ),
    ]
